# Generated by Django 4.0.7 on 2023-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_alter_site_area_hectares_alter_site_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
    ]
