# Generated by Django 4.0.7 on 2023-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0005_alter_site_area_hectares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
